export const CAMPSITES_LOADING = 'CAMPSITES_LOADING';
export const ADD_CAMPSITES = 'ADD_CAMPSITES';
export const CAMPSITES_FAILED = 'CAMPSITES_FAILED';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';

export const OFFERS_LOADING = 'OFFERS_LOADING';
export const ADD_OFFERS = 'ADD_OFFERS';
export const OFFERS_FAILED = 'OFFERS_FAILED';

export const WANTS_LOADING = 'WANTS_LOADING';
export const ADD_WANTS = 'ADD_WANTS';
export const WANTS_FAILED = 'WANTS_FAILED';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE'; 
